---
- name: Desplegar Docker Compose en Servidor Remoto
  hosts: ec2_es00  
  become: true  # Ejecutar como root

  tasks:
    - name: Crear directorio de la aplicación en el servidor
      file:
        path: /opt/app
        state: directory
        mode: '0755'

    - name: Copiar archivo docker-compose.yml al servidor
      copy:
        src: ./docker-compose.yml
        dest: /opt/app/docker-compose.yml
        mode: '0644'

    - name: Copiar archivo .env al servidor
      copy:
        src: ./env
        dest: /opt/app/.env
        mode: '0644'

    - name: Levantar el servicio con Docker Compose
      shell: |
        cd /opt/app
        docker compose up -d
      args:
        executable: /bin/bash
