---
- name: Desplegar Docker Compose en Servidor Remoto
  hosts: ec2_es02
  become: true  # Ejecutar como root

  tasks:
    - name: Crear directorio de la aplicación en el servidor
      file:
        path: /opt/app
        state: directory
        mode: '0755'

    - name: Copiar archivo docker-compose.yml al servidor
      copy:
        src: ./docker-compose.yml
        dest: /opt/app/docker-compose.yml
        mode: '0644'

    - name: Copiar archivo .env al servidor
      copy:
        src: ./env
        dest: /opt/app/.env
        mode: '0644'

    - name: Copiar archivo certs.tar.gz al servidor
      copy:
        src: ../certs_backup/certs.tar.gz
        dest: /opt/app/certs.tar.gz
        mode: '0644'

    - name: Descomprimir el archivo en el servidor
      ansible.builtin.unarchive:
        src: /opt/app/certs.tar.gz
        dest: /opt/app/
        remote_src: yes  # Indica que el archivo ya está en el servidor

    - name: Levantar el servicio con Docker Compose
      shell: |
        cd /opt/app
        docker compose up -d
      args:
        executable: /bin/bash
